### ISSUE TITLE
Diverses

### ISSUE THREAD

**Issue by Thomas4170** [jhughes1010/weather#1]
Hello, I have adapted the original code and expanded it with MQTT. I removed Blynk and Thingspeak, I don't need that. I use a bigger solar panel https://www.amazon.de/gp/product/B00XHREE50/ref=ppx_yo_dt_b_asin_title_o02_s02?ie=UTF8&psc=1 with a converter https://www.amazon.de/12V-24V-auf-Abw%C3%A4rtswandler-AC-DC-Abw%C3%A4rtsstromversorgungsmodul/dp/B07TVNMHQQ/ref=pd_b2b_qd_subs_6/262-8168895-0964553?pd_rd_w=SlpIJ&pf_rd_p=0a01ce9b-e0eb-4d44-83ff-4da6cd0d0d84&pf_rd_r=N1FRTER64CF9DAM6BRCS&pd_rd_r=55d530ac-031e-4281-b2f0-aaffb047b925&pd_rd_wg=JOknz&pd_rd_i=B07TVNMHQQ&psc=1 . Power supply has been extended to 2 batteries (parallel connection). The sketch works, but I have big problems with deep sleep. In your sketch I don't understand the "secrets.h", can you explain that for a beginner?

Greetings from Germany
Thomas

**Comment by jhughes1010** [comment]
Sorry I missed this, but it's probably easier to communicate via GitHub than in the instructables comments. See my answer from there for now.

**Comment by notecp** [comment]
is the MQTT in the current code?
@Thomas4170 why did you choose a solar panel which is not matching the DIY design? Is there one which is fitting to the design?
@jhughes1010 do you have access to the cad files for the 3d objects in order to manipulate? if so could you please upload them so we have one complete repository for this nice project?

**Comment by jhughes1010** [comment]
@notecp Look at my dev branch for current work in progress. Thomas and I have made great progress to stabilize operation. Any questions on software support are welcome and feedback is encouraged. I’m not the project author and am currently just doing stability testing on hardware and software at the moment. I do not have the 3D files and am using a waterproof ABS outdoor box for my testing.

**Comment by notecp** [comment]
good, maybe i´ll give it a try when the new pcb is designed.
for the 3d files: they are downloadable, but right now i am planning to make a solarpanel extender printable. simply a dish on which further panel (of the same type) can get mounted and connected in parallel. this is to cover the fewer sunny moments in Germany compared to India :)

**Comment by Thomas4170** [comment]
> 
> 
> @jhughes1010 is the MQTT in the current code?
> @Thomas4170 why did you choose a solar panel which is not matching the DIY design? Is there one which is fitting to the design?

There is a solar panel that fits the project but I won't print the case because I swapped the BH1750 for a photo resistor. I am also convinced that the original solar panel does not work in Germany. In winter the sun is low and the few hours to charge the battery are not enough

**Comment by notecp** [comment]
> There is a solar panel that fits the project but I won't print the case because I swapped the BH1750 for a photo resistor. I am also convinced that the original solar panel does not work in Germany. In winter the sun is low and the few hours to charge the battery are not enough

this is why i may design these "extension" panelholders for connecting more solarpanels in parallel.
why did you swap the bh1750 and for which photoresistor?

**Comment by Thomas4170** [comment]
I believe that the type of assembly of the BH1750 and the circuit board is not tight in the long run and problems then arise. My circuit board comes in a completely closed housing and only the BME / BMP and the photo resistor (https://www.amazon.de/gp/product/B089YN8W1F/ref=ppx_yo_dt_b_asin_title_o08_s01?ie=UTF8&psc=1) are in a protective housing (https : //www.amazon.de/TFA-Dostmann-Schutzh%C3%BClle-98-1114-02-montieren/dp/B017ILZF6C/ref=pd_d_sim_b2b_1/258-1832759-5571800? pd_rd_w = SH6yi & pf_43bf-332085d47bf -8249-f84411c898b8 & pf_rd_r = 7PWMFFXGAC8N1PR0DJ4V & pd_rd_r = 40d8e91d-91ff-426c-8e54-ab905bbfae55 & pd_rd_wg = kZEtZ & pd_rdsci = 1C & pD_rdsci = B017ILZ). If you want to see pictures then please PM
th.krebs@industrie-haus-service.com
