### ISSUE TITLE
Json format payload for MQTT messages?

### ISSUE THREAD

**Issue by Seeelefant** [jhughes1010/weather#15]
Are you planning tro introduce Json format payload for MQTT messages as described her https://arduinojson.org/v6/how-to/use-arduinojson-with-pubsubclient/ ?

**Comment by jhughes1010** [comment]
not in my queue. Moving on to a LORA and LoRaWAN version of the project now.

**Comment by Seeelefant** [comment]
Makes absolutely sense, maybe I can help a little in that direction.

**Comment by jhughes1010** [comment]
If you wish to add the json over MQTT, feel free to fork the project and submit a pull request when done. I'm interested in hearing your use case.
