### ISSUE TITLE
mqtt messages

### ISSUE THREAD

**Issue by javiermitchell** [jhughes1010/weather#16]
I'm trying to integrate the weather station sensor data into homeassistant via MQTT ( after enabling MQTT on secrets file)
Using mqtt explorer I can see updates every 5 minutes, or so
However, I cannot see anything if I susbscibe to any of the topics
I'm not sure if I'm doing something wrong or maybe the station is sending the messages in an "stange" way?
Thanks

**Comment by jhughes1010** [comment]
Try typing a forward slash after the topic name (in /config/configuration.yaml) if not already there.

**Comment by javiermitchell** [comment]
James
This is my yaml configuration:
mqtt:  sensor:  
### WeatherStation Stats MQTT
## WeatherStation Battery Voltage    - state_topic: "WeatherStation/batteryVoltage"      name: Battery Voltage      unit_of_measurement: 'V'
## WeatherStation batteryADC    - state_topic: "WeatherStation/batteryADC"      name: batteryADC     
## WeatherStation Wifi Signal    - state_topic: "WeatherStation/rssi"      name: Wifi Signal      unit_of_measurement: 'db'
## WeatherStation Ext Temperature    - state_topic: "WeatherStation/temperatureC"      name: Ext Temperature      unit_of_measurement: 'ºC'
## WeatherStation Wind Speed    - state_topic: "WeatherStation/windSpeed"      name: Wind Speed      unit_of_measurement: 'Kn'

I was also asking about some of the sensors that are not documented
Javier
    On Thursday, 29 September 2022 at 11:13:55 BST, James Hughes ***@***.***> wrote:  
 
 


Try typing a forward slash after the topic name (in /config/configuration.yaml) if not already there.

**Comment by Jimcam65** [comment]
Hello Javier,
Home Assistant just changed how to interpret mqtt now....this is what works for me:

mqtt:
  sensor:
   - name: "Solar rssi"
     state_topic: "MainTopic/rssi/"
     unit_of_measurement: 'db'
   - name: "Solar Temp F"
     state_topic: "MainTopic/temperatureF/"
     unit_of_measurement: '°F'
   - name: "Solar WindSpeed"

The / goes at the end of the state topic and now everything falls under mqtt then whatever it is a sensor a binary sensor etc..nake sure the spacing is correct as well.
Jim Miller

**Comment by javiermitchell** [comment]
Hi james, after I changed the HA MQQ config to add the trailing backslash, I can now see the sensors on HA
However, no matter what I do I cannot see the wind speed and wind direction being sent via MQTT, I have tested the signal on a oscilloscope on pins 14 (wind speed ) and 35 ( win dir) and is OK. 
As I said , I'm using board v3.3, so I wonder if the configuration is monitoring the wrong pins on thw wroom-32. Thanks again

**Comment by jhughes1010** [comment]
Let me take a look into this. Honestly, I do not think I have done anything with those in HA yet. 

James

**Comment by javiermitchell** [comment]
Thanks James
I figured it was because my board was not using the default dev kit pinout, so added  a #define KREBS_PCB in my secrets.h file, however when I try to compile I get a lot of errors as there is a lot variables not defined for this instance
Let me know If this is not the right approach

**Comment by javiermitchell** [comment]
Just to confirm: the issue is that the station does not send the MQTT data for wind sensors .
If I check MQTT Explorer the topic is there , but no data 
Thanks again

**Comment by jhughes1010** [comment]
Both speed and direction are not working for you?

James

**Comment by javiermitchell** [comment]
yes, none are working.
I have not check- yet - the rain sensor

Thanks

**Comment by jhughes1010** [comment]
I verified wind speed and direction are working and viewable in MQTT explorer on my end. Start with the serial console logs, wind speed and direction are present there.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/585299/193234583-886a0d44-9c98-4e0c-9f82-fa07afef8cff.png">

**Comment by jhughes1010** [comment]
Also, would not hurt to get a rain sensor checked out. With the sensor plugged in, just tip it and watch the serial console report that the station woke up for rain tip count update. 

Do not use the #define KREBS_PCB unless you have a PCB from Thomas Krebs

**Comment by javiermitchell** [comment]
James
I wil also check rain sensor
I thought the serial console was disabled
Thanks for checking
I will let you know if I find out

**Comment by javiermitchell** [comment]
I thought the serial port was sidabled as I could not see anything before
I connected the rain sensor, which wakes up the device, however, it seems it goes straight back to sleep:
Wakeup caused by external signal using RTC_IO



Going to sleep now...
Waking in 253 seconds

If I move the rain bucket again, the pattern is repeated
maybe is sleeeping ALL the time?

**Comment by javiermitchell** [comment]
OK, I left the serial port connected until it woke up, now i'm seeing:
10:43:58.929 -> ----- Sensor Statuses -----
10:43:58.975 -> BME status:         1
10:43:58.975 -> UV status:          1
10:43:58.975 -> lightMeter status:  1
10:43:58.975 -> temperature status: 1
10:43:58.975 -> 
10:43:58.975 -> Date:30 09 2022 Time: 04:44:02
10:43:58.975 -> Time to next wake: 298 seconds
10:43:58.975 -> No Wind dataWindSpeed: 0.000000
10:43:58.975 -> Analog value: 559 Wind direction: 202.5  
and MQTT:
10:43:59.300 -> WeatherStation/windSpeed/:  0.000
10:43:59.300 -> MQTT status: 1
10:43:59.347 -> WeatherStation/windDirection/: 202
10:43:59.347 -> MQTT status: 1
10:43:59.392 -> WeatherStation/windCardinalDirection/: SSW

So, it looks correct, except that there IS WIND speed and is reporting zero.
How I can further troubleshoot it? 
As I said, I had a scope on that pin and all look good
Thanks again

**Comment by jhughes1010** [comment]
First, the easy answer: the tip pin for the rain gauge wakes, increments a counter, then sleeps. It will get accumulated and sent with sensor data on the timer WAKE event.

The anemometer must be spinning when the device wakes. The station is incapable of monitoring wind while sleeping. I spin it manually while the device is awake to see wind speed. 

James

**Comment by javiermitchell** [comment]
James
Sorry to have bothered you
You are absolutely right: I thought the anemometer WAS spinning when it woke up, but it wasn't!
I Think I got it now
Thanks for your help  -and patience - with me

**Comment by jhughes1010** [comment]
No worries! We have plans for more interesting wind measurement actions, but they will take power for more frequent sampling from the sensor. Stay tuned!

**Comment by javiermitchell** [comment]
Great!!
Thanks, I will do
Any interesting insights for HA?

**Comment by jhughes1010** [comment]
I’m bare minimum user with HA. I was happy to see my data and create a fuel gauge for the battery level😂James HughesOn Sep 30, 2022, at 7:46 AM, javiermitchell ***@***.***> wrote:﻿
Great!!
Thanks, I will do
Any interesting insights for HA?
