### ISSUE TITLE
Explain pls :)

### ISSUE THREAD

**Issue by L0cutus** [jhughes1010/weather#17]
Hello!

``` 
 //Average samples
  if (msTotal > 0 && samples > 0)
  {
    windSpeed = 1.49 * 1000 / (msTotal / samples);
  }
```
Can you explain the expression: 1.49 * 1000 / (msTotal / samples) ?

```
#ifdef METRIC
  windSpeed =  windSpeed * 1.60934;
#endif
  MonPrintf("WindSpeed: %f\n", windSpeed);
  windSpeed = int((windSpeed + .05) * 10) / 10;
```
and also: int((windSpeed + .05) * 10) / 10;

Thanks!

**Comment by jhughes1010** [comment]
Let's start with the second question first as that calculation is more easy to explain. I'm rounding to the nearest 10th on windSpeed. Adding 5/100ths to the number takes care of the possible round up. Multiply by by 10, retrieve the truncated integer, then divide by 10 to get back to the original number.

I'll break down the other with attachment on UOM analysis. I need to refresh on this.

**Comment by jhughes1010** [comment]
![F7ACFD9C-E547-4210-8FEE-43FA55FD6CF4_1_102_o](https://user-images.githubusercontent.com/585299/199198630-7181ecbe-f5ae-4bc5-a39b-0b69a636d657.jpeg)
 Here's the UOM analysis after the average ms/samples is calculated.

**Comment by L0cutus** [comment]
1.49 was for miles per hour?

**Comment by jhughes1010** [comment]
Yes, 1.49 , was derived. Datasheet gives 2.4kph, subsequent multiply my 1.609 (if metric) gets us back to the 2.4kph.

**Comment by L0cutus** [comment]
1.49 was for miles per hour?

> Yes, 1.49 , was derived. Datasheet gives 2.4kph, subsequent multiply my 1.609 (if metric) gets us back to the 2.4kph.

many thanks for reply, I'm also trying to build/program my weather station using PlatformIO and i have tried to build a multifile project like your project but wasn't so simple since I'm not a C/C++ developer at all :-)

**Comment by jhughes1010** [comment]
Good luck with your efforts!
