### ISSUE TITLE
UV sensor always produce 0.0000 data

### ISSUE THREAD

**Issue by javiermitchell** [jhughes1010/weather#18]
Even with a new sensor - SI1145 - I get the same results, so it is either the sensor I'm using is somehow incompatible, or something on the software is not right

**Comment by jhughes1010** [comment]
May I ask what software version you are using?James HughesOn Nov 13, 2022, at 8:44 AM, javiermitchell ***@***.***> wrote:﻿
Even with a new sensor - SI1145 - I get the same results, so it is either the sensor I'm using is somehow incompatible, or something on the software is not right

**Comment by jhughes1010** [comment]
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/585299/201556394-37bd7c49-280c-44a2-a2da-4bf8bc55f27a.png">

**Comment by javiermitchell** [comment]
James
I have managed to fix  the UV issueIt really threw me off that the version advertised was still v1.3.1 instad of v1.3.3I tried to to reuse my older secrets.h file, but you also ameded your version ( sec.h), so I had to use your file insteadAnyway all is working , so thanks very much for your quick response
Javier
    On Sunday, 13 November 2022 at 16:56:01 GMT, James Hughes ***@***.***> wrote:  
 
 

May I ask what software version you are using?James HughesOn Nov 13, 2022, at 8:44 AM, javiermitchell ***@***.***> wrote:﻿
Even with a new sensor - SI1145 - I get the same results, so it is either the sensor I'm using is somehow incompatible, or something on the software is not right

**Comment by jhughes1010** [comment]
Thanks for pointing that out. I'll package up 1.3.3 as a formal release packaage. Sorry for the confusion on that.

**Comment by jhughes1010** [comment]
I've made a formal update for 1.3.3
